CREATE TABLE CENTRO (
  COD_CENTRO       INT(10) PRIMARY KEY,
  DEN_CENTRO       VARCHAR(30) NOT NULL,
  DIRECCION_CENTRO VARCHAR(50),
  NIF_CENTRO       VARCHAR(9)  NOT NULL,
  NOMB_REPR        VARCHAR(50),
  DNI_REPR         VARCHAR(9),
  DIRECTOR_CENTRO  VARCHAR(50),
  LOC_CENTRO       VARCHAR(50),
  MUN_CENTRO       VARCHAR(50),
  PROV_CENTRO      VARCHAR(30),
  CP_CENTRO        INT(5),
  DAT_CENTRO       VARCHAR(50)
);

CREATE TABLE CICLO (
  CLAVE_CICLO INT(10) PRIMARY KEY,
  NOM_CICLO   VARCHAR(100) NOT NULL,
  CLAVE_FAM   INT(10)      NOT NULL,
  NOM_FAM     VARCHAR(50)  NOT NULL
);

CREATE TABLE CICLO_CENTRO (
  COD_CENTRO  INT(10),
  CLAVE_CICLO INT(10),
  CONSTRAINT cicloc_fk FOREIGN KEY (CLAVE_CICLO) REFERENCES CICLO (CLAVE_CICLO),
  CONSTRAINT centro_fk FOREIGN KEY (COD_CENTRO) REFERENCES CENTRO (COD_CENTRO)
);

CREATE TABLE GRUPO (
  COD_GRUPO   INT(10) PRIMARY KEY,
  CLAVE_CICLO INT(10) NOT NULL,
  CONSTRAINT ciclo_fk FOREIGN KEY (CLAVE_CICLO) REFERENCES CICLO (CLAVE_CICLO)
);

CREATE TABLE ESTUDIANTE (
  NUM_MAT INT(10) PRIMARY KEY,
  NOM     VARCHAR(30) NOT NULL,
  APELL1  VARCHAR(30) NOT NULL,
  APELL2  VARCHAR(30),
  DNI     VARCHAR(9)  NOT NULL UNIQUE
);

CREATE TABLE GRUPO_ESTUDIANTE (
  COD_GRUPO  INT(10) NOT NULL,
  NUM_MAT    INT(10) NOT NULL,
  ANO_ACADEM INT(4)  NOT NULL,
  CONSTRAINT grupo_fk FOREIGN KEY (COD_GRUPO) REFERENCES GRUPO (COD_GRUPO),
  CONSTRAINT matricula_fk FOREIGN KEY (NUM_MAT) REFERENCES ESTUDIANTE (NUM_MAT)
);

CREATE TABLE EMPRESA (
  NUM_CONV    INT(10) PRIMARY KEY,
  NOM_EMPR    VARCHAR(30)  NOT NULL,
  F_FIRMA     DATE,
  LOCALIDAD   VARCHAR(100) NOT NULL,
  DIRECCION   VARCHAR(500) NOT NULL,
  TUT_EMPR    VARCHAR(50),
  REPR_EMPR   VARCHAR(50),
  CORREO_EMPR VARCHAR(50)
);

CREATE TABLE TUTOR (
  NIF_TUTOR VARCHAR(9) PRIMARY KEY,
  NOM       VARCHAR(30) NOT NULL,
  APELL1    VARCHAR(30) NOT NULL,
  APELL2    VARCHAR(30)
);

CREATE TABLE EMPRESA_ESTUDIANTE (
  NUM_MAT  INT(10) NOT NULL,
  NUM_CONV INT(10) NOT NULL,
  CONSTRAINT mat_fk FOREIGN KEY (NUM_MAT) REFERENCES ESTUDIANTE (NUM_MAT),
  CONSTRAINT conv_fk FOREIGN KEY (NUM_CONV) REFERENCES EMPRESA (NUM_CONV)
);

CREATE TABLE ESTUDANTE_TUTOR (
  NUM_MAT   INT(10)    NOT NULL,
  NIF_TUTOR VARCHAR(9) NOT NULL,
  CONSTRAINT est_fk FOREIGN KEY (NUM_MAT) REFERENCES ESTUDIANTE (NUM_MAT),
  CONSTRAINT tutor_fk FOREIGN KEY (NIF_TUTOR) REFERENCES TUTOR (NIF_TUTOR)
);

CREATE TABLE USERS (
  NOMBRE VARCHAR(50),
  USR    VARCHAR(50) PRIMARY KEY,
  PWD    VARCHAR(260) NOT NULL,
  ROLE   TINYINT(1)   NOT NULL,
  MAIL   varchar(50)  NOT NULL
);


INSERT INTO CENTRO VALUES
  (1, 'UEM VILLAVICIOSA', 'C/ TAJO S/N', '89452147B', 'REPRESENTANTE 1', '70081495A', 'DIRECTOR1',
      'VILLAVICIOSA DE ODÓN', 'VILLAVICIOSA DE ODÓN', 'MADRID', 28670, 'DAT SUR');

INSERT INTO CICLO VALUES (84, 'DESARROLLO DE APLICACIONES MULTIPLATAFORMA', 486644, 'INFORMÁTICA');

INSERT INTO CICLO_CENTRO VALUES (1, 84);

INSERT INTO GRUPO VALUES (10, 84);

INSERT INTO ESTUDIANTE VALUES (28756432, 'Adrián', 'García', 'García', '84265175I');

INSERT INTO GRUPO_ESTUDIANTE VALUES (10, 28756432, 2018);

INSERT INTO EMPRESA VALUES
  (4656, 'Accenture', STR_TO_DATE('12-12-2017', '%d-%m-%Y'), 'Alcobendas', 'Calle Principal 1', 'Alberto García',
   'Theresa May', 'ASDADSASD@GMAIL.COM');

INSERT INTO TUTOR VALUES ('45612378A', 'Pedro', 'Camacho', 'Ortega');

INSERT INTO EMPRESA_ESTUDIANTE VALUES (28756432, 4656);

INSERT INTO ESTUDANTE_TUTOR VALUES (28756432, '45612378A');

/*Usuarios de prueba, sla contraseña es "contraseña", se inserta el hash que desde la aplicación se inserta al generar usuarios.*/
INSERT INTO USERS VALUES
  ('Pedro Camacho', 'tutor', 'edf9cf90718610ee7de53c0dcc250739239044de9ba115bb0ca6026c3e4958a5', 0,
   'julenwhite@icloud.com');
INSERT INTO USERS VALUES
  ('Ana Manzanero', 'administrativo', 'edf9cf90718610ee7de53c0dcc250739239044de9ba115bb0ca6026c3e4958a5', 1,
   'julenwhite@icloud.com');
INSERT INTO USERS VALUES ('Superusuario', 'root', 'edf9cf90718610ee7de53c0dcc250739239044de9ba115bb0ca6026c3e4958a5', 2,
                          'julenwhite@icloud.com');
