CREATE TABLE CENTRO (
  COD_CENTRO       INT(10) PRIMARY KEY,
  DEN_CENTRO       VARCHAR(30) NOT NULL,
  DIRECCION_CENTRO VARCHAR(50),
  NIF_CENTRO       VARCHAR(9)  NOT NULL,
  NOMB_REPR        VARCHAR(50),
  DNI_REPR         VARCHAR(9),
  DIRECTOR_CENTRO  VARCHAR(50),
  LOC_CENTRO       VARCHAR(50),
  MUN_CENTRO       VARCHAR(50),
  PROV_CENTRO      VARCHAR(30),
  CP_CENTRO        INT(5),
  DAT_CENTRO       VARCHAR(50)
);

CREATE TABLE CICLO (
  CLAVE_CICLO INT(10) PRIMARY KEY,
  NOM_CICLO   VARCHAR(100) NOT NULL,
  CLAVE_FAM   INT(10)      NOT NULL,
  NOM_FAM     VARCHAR(50)  NOT NULL
);

CREATE TABLE CICLO_CENTRO (
  COD_CENTRO  INT(10),
  CLAVE_CICLO INT(10),
  CONSTRAINT cicloc_fk FOREIGN KEY (CLAVE_CICLO) REFERENCES CICLO (CLAVE_CICLO),
  CONSTRAINT centro_fk FOREIGN KEY (COD_CENTRO) REFERENCES CENTRO (COD_CENTRO)
);

/*
Vista Tutor (Tabla asignados y no asignados):
SELECT NOM, APELL1, APELL2 FROM ESTUDIANTE, GRUPO_ESTUDIANTE WHERE COD_GRUPO = ? AND ESTUDIANTE.NUM_MAT = GRUPO_ESTUDIANTE.NUM_MAT AND ESTUDIANTE.NUM_MAT IN (SELECT NUM_MAT FROM EMPRESA_ESTUDIANTE);
Vista Prácticas:
SELECT ESTUDIANTE.NOM, NOM_EMPR, TUT_EMPR, FECHA_INICIO, FECH_FIN, HORARIO, LOCALIZACION, ERASMUS, ESTADO FROM EMPRESA_ESTUDIANTE, ESTUDIANTE, EMPRESA;*/
CREATE TABLE ESTUDIANTE (
  NUM_MAT INT(10) PRIMARY KEY,
  NOM     VARCHAR(30) NOT NULL,
  APELL1  VARCHAR(30) NOT NULL,
  APELL2  VARCHAR(30),
  DNI     VARCHAR(9)  NOT NULL UNIQUE
);

/*SELECT ESTUDIANTE.NOM, NOM_EMPR, TUT_EMPR, FECHA_INICIO, FECH_FIN, HORARIO, LOCALIZACION, ERASMUS, ESTADO FROM EMPRESA_ESTUDIANTE, ESTUDIANTE, EMPRESA;*/
CREATE TABLE EMPRESA (
  NUM_CONV    INT(10) PRIMARY KEY,
  NOM_EMPR    VARCHAR(30)  NOT NULL,
  F_FIRMA     DATE,
  LOCALIDAD   VARCHAR(100) NOT NULL,
  DIRECCION   VARCHAR(500) NOT NULL,
  REPR_EMPR   VARCHAR(50),
  CORREO_EMPR VARCHAR(50)
);

CREATE TABLE TUTOR (
  NIF_TUTOR VARCHAR(9) PRIMARY KEY,
  NOM       VARCHAR(30) NOT NULL,
  APELL1    VARCHAR(30) NOT NULL,
  APELL2    VARCHAR(30)
);

/*
Vista de Prácticas:
SELECT ESTUDIANTE.NOM, NOM_EMPR, TUT_EMPR, FECHA_INICIO, FECH_FIN, HORARIO, LOCALIZACION, ERASMUS, ESTADO FROM EMPRESA_ESTUDIANTE, ESTUDIANTE, EMPRESA;
Vista Tutor (Tabla asignados y no asignados)
SELECT NOM, APELL1, APELL2 FROM ESTUDIANTE, GRUPO_ESTUDIANTE WHERE COD_GRUPO = ? AND ESTUDIANTE.NUM_MAT = GRUPO_ESTUDIANTE.NUM_MAT AND ESTUDIANTE.NUM_MAT IN (SELECT NUM_MAT FROM EMPRESA_ESTUDIANTE);*/
CREATE TABLE EMPRESA_ESTUDIANTE (
  NUM_MAT      INT(10) NOT NULL,
  NUM_CONV     INT(10) NOT NULL,
  TUT_EMPR     VARCHAR(50),
  FECHA_INICIO DATE,
  FECH_FIN     DATE,
  HORARIO      VARCHAR(50),
  LOCALIZACION VARCHAR(100),
  ERASMUS      BOOLEAN,
  CONSTRAINT mat_fk FOREIGN KEY (NUM_MAT) REFERENCES ESTUDIANTE (NUM_MAT),
  CONSTRAINT conv_fk FOREIGN KEY (NUM_CONV) REFERENCES EMPRESA (NUM_CONV)
);

CREATE TABLE ESTUDANTE_TUTOR (
  NUM_MAT   INT(10)    NOT NULL,
  NIF_TUTOR VARCHAR(9) NOT NULL,
  CONSTRAINT est_fk FOREIGN KEY (NUM_MAT) REFERENCES ESTUDIANTE (NUM_MAT),
  CONSTRAINT tutor_fk FOREIGN KEY (NIF_TUTOR) REFERENCES TUTOR (NIF_TUTOR)
);

CREATE TABLE USERS (
  NOMBRE VARCHAR(50),
  USR    VARCHAR(50) PRIMARY KEY,
  PWD    VARCHAR(260) NOT NULL,
  ROLE   TINYINT(1)   NOT NULL,
  MAIL   varchar(50)  NOT NULL
);


CREATE TABLE GRUPO (
  NOM_GRUPO   VARCHAR(50) NOT NULL,
  COD_GRUPO   INT(10) PRIMARY KEY,
  CLAVE_CICLO INT(10)     NOT NULL,
  USR         VARCHAR(50),
  CONSTRAINT ciclo_fk FOREIGN KEY (CLAVE_CICLO) REFERENCES CICLO (CLAVE_CICLO),
  CONSTRAINT tutor_grupo_fk FOREIGN KEY (USR) REFERENCES USERS (USR)
);
/*
Vista Tutor (Tabla asignados y no asignados):
SELECT NOM, APELL1, APELL2 FROM ESTUDIANTE, GRUPO_ESTUDIANTE WHERE COD_GRUPO = ? AND ESTUDIANTE.NUM_MAT = GRUPO_ESTUDIANTE.NUM_MAT AND ESTUDIANTE.NUM_MAT IN (SELECT NUM_MAT FROM EMPRESA_ESTUDIANTE);

 */
CREATE TABLE GRUPO_ESTUDIANTE (
  COD_GRUPO  INT(10) NOT NULL,
  NUM_MAT    INT(10) NOT NULL,
  ANO_ACADEM INT(4)  NOT NULL,
  CONSTRAINT grupo_fk FOREIGN KEY (COD_GRUPO) REFERENCES GRUPO (COD_GRUPO),
  CONSTRAINT matricula_fk FOREIGN KEY (NUM_MAT) REFERENCES ESTUDIANTE (NUM_MAT)
);


INSERT INTO CENTRO VALUES
  (1, 'UEM VILLAVICIOSA', 'C/ TAJO S/N', '89452147B', 'REPRESENTANTE 1', '70081495A', 'DIRECTOR1',
      'VILLAVICIOSA DE ODÓN', 'VILLAVICIOSA DE ODÓN', 'MADRID', 28670, 'DAT SUR');

INSERT INTO CICLO VALUES (84, 'DESARROLLO DE APLICACIONES MULTIPLATAFORMA', 486644, 'INFORMÁTICA');

INSERT INTO CICLO_CENTRO VALUES (1, 84);

INSERT INTO ESTUDIANTE VALUES (28756432, 'Adrián', 'García', 'García', '84265175I');
INSERT INTO ESTUDIANTE VALUES (28756434, 'Julen', 'Bujanda', 'Blanco', '84265275I');
INSERT INTO ESTUDIANTE VALUES (28756436, 'Iván', 'Hernández', '', '84267175I');
INSERT INTO ESTUDIANTE VALUES (28756438, 'Víctor', 'Jiménez', '', '88265175I');
INSERT INTO ESTUDIANTE VALUES (28756440, 'Andrés', 'Murillas', '', '84265155I');

INSERT INTO EMPRESA VALUES
  (4656, 'Accenture', STR_TO_DATE('12-12-2017', '%d-%m-%Y'), 'Alcobendas', 'Calle Principal 1',
   'Theresa May', 'ASDADSASD@GMAIL.COM');

INSERT INTO TUTOR VALUES ('45612378A', 'Pedro', 'Camacho', 'Ortega');

INSERT INTO EMPRESA_ESTUDIANTE VALUES
  (28756432, 4656, 'Donald Trump', STR_TO_DATE('12-12-2017', '%d-%m-%Y'), STR_TO_DATE('20-04-2018', '%d-%m-%Y'),
   '8AM-5PM', 'Brighton', TRUE);

INSERT INTO ESTUDANTE_TUTOR VALUES (28756432, '45612378A');

/*Usuarios de prueba, la contraseña es "contraseña", se inserta el hash que desde la aplicación se inserta al generar usuarios.*/
INSERT INTO USERS VALUES
  ('Pedro Camacho', 'tutor', 'edf9cf90718610ee7de53c0dcc250739239044de9ba115bb0ca6026c3e4958a5', 0,
   'julenwhite@icloud.com');
INSERT INTO USERS VALUES
  ('Raúl Rodríguez', 'raul', 'edf9cf90718610ee7de53c0dcc250739239044de9ba115bb0ca6026c3e4958a5', 0,
   'julenwhite@icloud.com');
INSERT INTO USERS VALUES
  ('Ana Manzanero', 'director', 'edf9cf90718610ee7de53c0dcc250739239044de9ba115bb0ca6026c3e4958a5', 1,
   'julenwhite@icloud.com');
INSERT INTO USERS VALUES ('Superusuario', 'root', 'edf9cf90718610ee7de53c0dcc250739239044de9ba115bb0ca6026c3e4958a5', 2,
                          'julenwhite@icloud.com');

INSERT INTO GRUPO VALUES ('DAM2-1718', 10, 84, 'tutor');
INSERT INTO GRUPO VALUES ('DAM2-1617', 20, 84, 'raul');

INSERT INTO GRUPO_ESTUDIANTE VALUES (10, 28756432, 2018);
INSERT INTO GRUPO_ESTUDIANTE VALUES (10, 28756434, 2018);
INSERT INTO GRUPO_ESTUDIANTE VALUES (10, 28756436, 2018);
INSERT INTO GRUPO_ESTUDIANTE VALUES (20, 28756438, 2017);
INSERT INTO GRUPO_ESTUDIANTE VALUES (20, 28756440, 2017);
